###
# This is the place to override the php cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "php/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
packages = [
  'php5-apcu', 'php5-gd', 'php5-mcrypt', 'php5-curl'
]